### ISSUE TITLE
drop_upload() delays

### ISSUE THREAD

**Issue by deanl1** [karthik/rdrop2#146]
Has anyone else had issues with the running of drop_upload() function recently?  I have code that has worked perfectly well for a while, an is still producing the messages "uploaded successfully", but it usually takes around 30 seconds to appear in my drop box account. dropbox doesn't seem to be having any issues lately (https://status.dropbox.com/).

**Comment by ClaytonJY** [comment]
@deanl1 where are you looking that you're seeing a delay, the web UI or your local dropbox folder?

When using the web UI, I've seen the view be delayed in updating, so a manual refresh of the page is sometimes needed.

If it's taking a while to get to your local dropbox synced folder, that's probably due to the connection between you and Dropbox.

Either way, I don't think this has anything to do with `rdrop2`; if you're getting the "uploaded successfully" message, then Dropbox has told us it received the file, and anything past that is out of our control.

**Comment by deanl1** [comment]
Thanks for the reply.  The delay is in actually uploading. I look in my drop box account online and it doesn't update for a while after "upload successful". I am using the package for teaching R - I upload my script file to drop box so the students can access it, so the process needs to be fairly quick.

**Comment by ClaytonJY** [comment]
@deanl1 if you're getting the "uploaded successfully" message, then the file has been given to Dropbox's servers. Anything after that is out of our control, so if the delay occurs afterwards there's nothing we can do to remedy that in `rdrop2`. Sorry!
