### ISSUE TITLE
Get version history

### ISSUE THREAD

**Issue by noamross** [karthik/rdrop2#4]
I would very much like to be able to programmatically retrieve the version history of a dropbox file.  I suggest a `drop_history()` command, which would list the version history of a file, and then an argument to drop get, e.g., `drop_get(..., version = VERSION)`.  We do this in `driver`, and `version` can either take the version number or a date, in which case it will retrieve the last version prior to that date.

**Comment by karthik** [comment]
Excellent idea @noamross!
There are a handful of features I have left aside for the next milestone. For now, I just wanted to get the basic interface up and go from there. Engineering too much before anyone used it in the real world would have been a problem. Versions are a bit opaque (since there is no commit message attached to them) but date would be a good approximation. I'll add this to the next milestone.

**Comment by karthik** [comment]
@noamross I've added this feature now. Closing this issue unless you come across any issues.
